[package]
name = "guess"
version = "0.1.0"
authors = ["Stefan Langenmaier <stefan.langenmaier@makandra.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"

[[bin]]
name = "guess"
path = "src/guess.rs"
